# Generated by Django 3.2.7 on 2021-09-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название товара')),
                ('receipt_date', models.DateField(verbose_name='Дата поступления')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('unit', models.CharField(max_length=16, verbose_name='Единица измерения')),
                ('supplier_name', models.CharField(max_length=64, verbose_name='Имя поставщика')),
            ],
        ),
    ]
