# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QAction, QWidget


class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 761, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.db_path = QtWidgets.QTextBrowser(self.frame)
        self.db_path.setEnabled(False)
        self.db_path.setGeometry(QtCore.QRect(140, 10, 491, 21))
        self.db_path.setObjectName("db_path")

        self.db_label = QtWidgets.QLabel(self.frame)
        self.db_label.setGeometry(QtCore.QRect(0, 10, 121, 16))
        self.db_label.setObjectName("db_label")

        self.selectDb = QtWidgets.QPushButton(self.frame)
        self.selectDb.setGeometry(QtCore.QRect(660, 10, 91, 23))
        self.selectDb.setObjectName("selectDb")

        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(25, 61, 631, 471))
        self.tableView.setObjectName("tableView")
        self.addRecord = QtWidgets.QPushButton(self.centralwidget)
        self.addRecord.setGeometry(QtCore.QRect(690, 180, 75, 23))
        self.addRecord.setObjectName("addRecord")
        self.removeRecord = QtWidgets.QPushButton(self.centralwidget)
        self.removeRecord.setGeometry(QtCore.QRect(690, 280, 75, 23))
        self.removeRecord.setObjectName("removeRecord")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")

        self.categories = QAction(self)
        # self.categories = QtWidgets.QMenu(self.menubar)
        self.categories.setEnabled(False)
        # self.categories.setObjectName("categories")

        self.units = QAction(self)
        # self.units = QtWidgets.QMenu(self.menubar)
        self.units.setEnabled(False)
        # self.units.setObjectName("units")

        self.positions = QAction(self)
        # self.positions = QtWidgets.QMenu(self.menubar)
        self.positions.setEnabled(False)
        # self.positions.setObjectName("positions")

        self.goods = QAction(self)
        # self.goods = QtWidgets.QMenu(self.menubar)
        self.goods.setEnabled(False)
        # self.goods.setObjectName("goods")

        self.employees = QAction(self)
        # self.employees = QtWidgets.QMenu(self.menubar)
        self.employees.setEnabled(False)
        # self.employees.setObjectName("employees")

        self.vendors = QAction(self)
        # self.vendors = QtWidgets.QMenu(self.menubar)
        self.vendors.setEnabled(False)
        # self.vendors.setObjectName("vendors")

        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.categories)
        self.menubar.addAction(self.units)
        self.menubar.addAction(self.positions)
        self.menubar.addAction(self.goods)
        self.menubar.addAction(self.employees)
        self.menubar.addAction(self.vendors)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.db_label.setText(_translate("MainWindow", "Путь к базе данных"))
        self.selectDb.setText(_translate("MainWindow", "Выбрать"))
        self.addRecord.setText(_translate("MainWindow", "Добавить"))
        self.removeRecord.setText(_translate("MainWindow", "Удалить"))
        self.categories.setText(_translate("MainWindow", "Категории товаров"))
        self.units.setText(_translate("MainWindow", "Единицы измерения товаров"))
        self.positions.setText(_translate("MainWindow", "Должности"))
        self.goods.setText(_translate("MainWindow", "Товары"))
        self.employees.setText(_translate("MainWindow", "Сотрудники"))
        self.vendors.setText(_translate("MainWindow", "Поставщики"))